const __ = require('underscore');

const CONST = {
  PRODUCT_TYPE_NAME_TO_ID_HASH: {
    COMIC: 1,
    DATING_SERVICE: 2,
    CONSOLE_GAME: 3,
    NOVEL: 4,
    IT: 5,
    INN_RESERVATION: 6,
    PORTABLE_GAME: 7,
    ANIME: 8,
    MOVIE: 9,

    ALL: 999,
  },

  PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH: {
    BOOK: 1,
    GAME: 2,
    DATING: 3,
    INN: 4,
    ANIME: 5,
    MOVIE: 6,

    ALL: 999,
  },

  RANKING_TYPE_NAME_TO_ID_HASH: {
    BUZZ: 1,
  },

  ERROR_TYPE_NAME_TO_MESSAGE_HASH: {
    'DEFAULT': '内部エラーが発生しました',
    '404': 'お探しのページを見つけることができませんでした',
    'PAGE_EXCEEDED': '存在しないページ番号が指定されています',
    'IN_PREPARING_RANKING': '最新のランキングを生成中です。<br>しばらく経ってから再度アクセスしてください。',
  },

  CACHE_TWEET_NUM: 300,

  THRESHOLD_BUZZ_FOR_RANK_IN: 5,

  STR_LENGTH_FOR_CALC_LSD: 20,

  PRODUCT_NUM_PER_PAGE: 10,

  INITIAL_DISPLAY_TWEET_NUM_IN_RANKING: 3,

  TWEET_NUM_PER_PAGE_IN_TWITTER_ACCOUNT_PAGE: 20,

  DEPRIORITIZE_WORDS_IN_TWEET_TEXT: [
    '実況',
    '今日買った漫画',
    '#自分の趣味全開で',
    '交換',
    '譲渡',
    'お譲り',
    '譲って',
    '買取',
    '代行',
    '販売中',
    '入荷',
    'ご来店',
    'お取扱'
  ],

  IGNORE_STRINGS_FOR_FORMATTING_PRODUCT_NAME: [
    'Nintendo Switch版',
    'PS4版',
    'PS Vita版',
    '通常版',
    '完全生産限定版',
    '初回限定',
    'Nintendo 3DS版',
    'PlayStation Vita the Best',
    '完全版',
    '楽天ブックス限定特典付き',
  ],

  VALIDITY_STATUS_NAME_TO_ID_HASH: {
    NORMAL: 0,
    SUSPICIOUS: 1,
    PROTECTED: 2, // manually checked as valid product
    OVER_TWEET_COUNT_LIMIT: 3, // programmatically set by tweet_collector
    SUSPICIOUS_BY_ADDING_RELATED_PRODUCT: 4, // see db_util.js. need to check manually
    FAILED_TO_COLECT_TWEET: 5, // see tweet_collector.js
    UNDER_REVIEW: 6, // ex.. add alt serch word by users in product_detail.js
    MONITORING: 7, // monitoring for some reason
    ALONE: 8, // cannot be join by other products. solo bundle.
    SUSPICIOUS_BY_MECAB_ANALYSIS: 77,
    TEMP: 88, // temporary id for programmatically reason. this id shouldnt be found in DB
    INVALID: 99, // manually checked as "INVALID" product
  },

  ANIME_COUR_INTO_MONTH_HASH: {
    1: 1,
    2: 4,
    3: 7,
    4: 10,
  },
};

const REFERENCE_CONST = {
  VALIDITY_STATUS_ID_TO_NAME_HASH: __.invert(CONST.VALIDITY_STATUS_NAME_TO_ID_HASH),

  RANKING_TYPE_ID_TO_NAME_HASH: __.invert(CONST.RANKING_TYPE_NAME_TO_ID_HASH),

  PRODUCT_TYPE_ID_TO_NAME_HASH: __.invert(CONST.PRODUCT_TYPE_NAME_TO_ID_HASH),

  PRODUCT_TYPE_BUNDLE_ID_TO_NAME_HASH: __.invert(CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH),

  PRODUCT_TYPE_BUNDLE_ID_TO_PRODUCT_TYPE_IDS: {
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.BOOK]: [
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.COMIC,
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.NOVEL,
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.IT,
    ],
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.GAME]: [
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.CONSOLE_GAME,
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.PORTABLE_GAME,
    ],
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.INN]: [
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.INN_RESERVATION
    ],
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.DATING]: [
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.DATING_SERVICE
    ],
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ANIME]: [
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.ANIME
    ],
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.MOVIE]: [
      CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.MOVIE
    ],
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ALL]: __.values(CONST.PRODUCT_TYPE_NAME_TO_ID_HASH),
  },

  PRODUCT_TYPE_BUNDLE_ID_TO_JA_NAME_HASH: {
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ALL]: '総合',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.BOOK]: '本・書籍',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.GAME]: 'ゲーム',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.DATING]: '出会い',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.INN]: '宿泊・旅行予約',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ANIME]: 'アニメ',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.MOVIE]: '映画',
  },

  PRODUCT_TYPE_ID_TO_JA_NAME_HASH: {
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.ALL]: '全て',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.COMIC]: '漫画',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.NOVEL]: '小説',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.IT]: 'IT・プログラミング',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.DATING_SERVICE]: '出会い',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.CONSOLE_GAME]: '据え置き型ゲーム',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.INN_RESERVATION]: '宿泊・旅行予約サービス',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.PORTABLE_GAME]: '携帯ゲーム',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.ANIME]: 'アニメ',
    [CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.MOVIE]: '映画',
  },

  PRODUCT_TYPE_BUNDLE_ID_TO_FONT_AWESOME_CLASS: {
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ALL]: 'fas fa-globe',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.BOOK]: 'fas fa-book-reader',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.GAME]: 'fas fa-gamepad',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.DATING]: 'fas fa-heart',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.INN]: 'fas fa-hotel',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ANIME]: 'fab fa-earlybirds',
    [CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.MOVIE]: 'fas fa-film',
  },

  EXCEPTION_NO_BUZZ_NUM_THRESHOLD_PRODUCT_TYPE_IDS: [
    CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.DATING_SERVICE,
    CONST.PRODUCT_TYPE_NAME_TO_ID_HASH.INN_RESERVATION,
  ],

  VALID_STATUS_IDS: [
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.NORMAL,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.MONITORING,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.PROTECTED,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.ALONE,
  ],

  SHOULD_REVIEW_VALIDITY_STATUS_IDS: [
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.NORMAL,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.MONITORING,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.UNDER_REVIEW,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.FAILED_TO_COLECT_TWEET,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.SUSPICIOUS_BY_MECAB_ANALYSIS,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.SUSPICIOUS_BY_ADDING_RELATED_PRODUCT,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.SUSPICIOUS,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.OVER_TWEET_COUNT_LIMIT,
    CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.TEMP,
  ],

  NAV_BUNDLE_ID_ORDER: [
    CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ALL,
    CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.BOOK,
    CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.GAME,
    CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ANIME,
    CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.MOVIE,
    CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.INN,
    // CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.DATING, // disabled until end of Amazon examination
  ],
};

var REFERENCE_REFERENCE_CONST = {
  CAN_JOIN_VALIDITY_STATUS_IDS: (() => {
    var validityStatusIds = REFERENCE_CONST.VALID_STATUS_IDS;
    return __.without(validityStatusIds, CONST.VALIDITY_STATUS_NAME_TO_ID_HASH.ALONE);
  })(),

  PRODUCT_TYPE_ID_TO_BELONGED_PRODUCT_TYPE_BUNDLE_ID: (() => {
    var result = {};
    __.each(REFERENCE_CONST.PRODUCT_TYPE_BUNDLE_ID_TO_PRODUCT_TYPE_IDS, (productTypeIds, productTypeBundleId) => {
      if (productTypeBundleId == CONST.PRODUCT_TYPE_BUNDLE_NAME_TO_ID_HASH.ALL) return;
      __.each(productTypeIds, productTypeId => {
        result[productTypeId] = productTypeBundleId;
      });
    });
    return result;
  })(),
};

module.exports = __.extend(CONST, REFERENCE_CONST, REFERENCE_REFERENCE_CONST);
